"""expand urgency to four levels

Revision ID: 203687e66808
Revises: ff31ea6a7b39
Create Date: 2026-10-02 08:36:00.822806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203687e66808'
down_revision = 'ff31ea6a7b39'
branch_labels = None
depends_on = None


def upgrade():
    op.execute("UPDATE seeker_request SET urgency = 'high' WHERE urgency = 'urgent'")
    op.execute("UPDATE seeker_request SET urgency = 'medium' WHERE urgency = 'normal'")

    with op.batch_alter_table('seeker_request', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=6),
               type_=sa.Enum('low', 'medium', 'high', 'critical', name='urgency_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seeker_request', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.Enum('low', 'medium', 'high', 'critical', name='urgency_enum'),
               type_=sa.VARCHAR(length=6),
               existing_nullable=False)

    op.execute("UPDATE seeker_request SET urgency = 'urgent' WHERE urgency IN ('high', 'critical')")
    op.execute("UPDATE seeker_request SET urgency = 'normal' WHERE urgency IN ('medium', 'low')")

