"""initial schema

Revision ID: 793ed120b529
Revises: 
Create Date: 2026-05-29 12:25:56.945432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '793ed120b529'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
