"""convert_string_columns_to_enums

Revision ID: ff31ea6a7b39
Revises: 793ed120b529
Create Date: 2026-10-01 22:53:47.156384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff31ea6a7b39'
down_revision = '793ed120b529'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('pending', 'accepted', 'declined', name='match_status_enum'),
               existing_nullable=True)

    with op.batch_alter_table('seeker_request', schema=None) as batch_op:
        batch_op.alter_column('urgency',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('urgent', 'normal', name='urgency_enum'),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.Enum('open', 'fulfilled', 'cancelled', name='request_status_enum'),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.Enum('donor', 'seeker', name='user_type_enum'),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('user_type',
               existing_type=sa.Enum('donor', 'seeker', name='user_type_enum'),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)

    with op.batch_alter_table('seeker_request', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('open', 'fulfilled', 'cancelled', name='request_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
        batch_op.alter_column('urgency',
               existing_type=sa.Enum('urgent', 'normal', name='urgency_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)

    with op.batch_alter_table('match', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.Enum('pending', 'accepted', 'declined', name='match_status_enum'),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###
